export type ProjectLine = {
  code: string;
  purpose: string;
  parameters?: string;
};

export type IndustryProject = {
  slug: string;
  title: string;
  level: "Foundation" | "Intermediate" | "Industry";
  summary: string;
  businessUse: string;
  stack: string[];
  files: string[];
  runCommand: string;
  lines: ProjectLine[];
};

const L = (code: string, purpose: string, parameters?: string): ProjectLine => ({
  code,
  purpose,
  parameters,
});

export const industryProjects: IndustryProject[] = [
  {
    slug: "customer-churn-risk-report",
    title: "Customer Churn Risk Report",
    level: "Industry",
    summary:
      "Customer CSV ko validate karke risk score banata hai, plan-wise churn summary export karta hai, aur business report chart save karta hai.",
    businessUse:
      "Retention team high-risk customers identify karke offers, calls, ya support follow-up prioritize kar sakti hai.",
    stack: ["Python", "NumPy", "pandas", "Matplotlib"],
    files: [
      "data/customers.csv",
      "reports/churn/scored_customers.csv",
      "reports/churn/churn_summary.csv",
      "reports/churn/churn_rate_by_plan.png",
    ],
    runCommand: "python churn_risk_report.py",
    lines: [
      L(`from pathlib import Path`, "Filesystem paths ko OS-safe object ke form me handle karne ke liye import.", "`Path` me string path, joined path, absolute path, ya home-relative path pass kar sakte ho."),
      L(`import logging`, "Production-style status logs print karne ke liye standard library module.", "`logging` levels: DEBUG, INFO, WARNING, ERROR, CRITICAL."),
      L(`import numpy as np`, "Fast numeric operations, clipping, and safe division helpers ke liye NumPy import.", "Alias `np` convention hai; custom alias possible hai but team code me avoid karo."),
      L(`import pandas as pd`, "CSV read, tabular transforms, groupby summary, and exports ke liye pandas import.", "Alias `pd` industry convention hai."),
      L(`import matplotlib.pyplot as plt`, "Report chart generate aur save karne ke liye Matplotlib pyplot import.", "Alias `plt` convention hai."),
      L(`INPUT_FILE = Path("data/customers.csv")`, "Raw customer data ka source path central config me rakha.", "Yahan CSV path, absolute path, ya env se loaded path use kar sakte ho."),
      L(`REPORT_DIR = Path("reports/churn")`, "Saare generated reports ek predictable folder me save honge.", "Folder name date-based bhi ho sakta hai, jaise `reports/churn/2026-06-24`."),
      L(`CHURN_THRESHOLD = 0.65`, "High-risk customer decide karne ka business threshold.", "0 se 1 ke beech koi value; lower threshold recall badhata hai, higher threshold precision."),
      L(`logging.basicConfig(level=logging.INFO, format="%(levelname)s:%(message)s")`, "Logger ko readable format aur INFO level pe initialize karta hai.", "`level`, `format`, `filename`, `datefmt`, `filemode` pass kar sakte ho."),
      L(`def load_customers(path: Path) -> pd.DataFrame:`, "CSV loading aur schema validation ko reusable function me isolate karta hai.", "`path` ko `Path` ya compatible path-like object de sakte ho."),
      L(`    df = pd.read_csv(path, parse_dates=["signup_date", "last_login"])`, "CSV read karta hai aur date columns ko datetime me parse karta hai.", "`sep`, `usecols`, `dtype`, `parse_dates`, `na_values`, `encoding` pass kar sakte ho."),
      L(`    required = {"customer_id", "plan", "monthly_spend", "tickets_30d", "days_since_login", "is_churned"}`, "Minimum required columns set define karta hai.", "Business ke hisab se aur columns add kar sakte ho."),
      L(`    missing = required - set(df.columns)`, "Input file me kaunse required columns missing hain nikalta hai.", "Set difference me left side expected, right side actual columns hote hain."),
      L(`    if missing:`, "Invalid input ko early fail karne ke liye guard condition.", "Condition me empty set false hota hai, non-empty set true."),
      L(`        raise ValueError(f"Missing columns: {sorted(missing)}")`, "Clear error deta hai taaki bad CSV silently process na ho.", "`ValueError` ke alawa custom exception bhi raise kar sakte ho."),
      L(`    return df.drop_duplicates(subset="customer_id").copy()`, "Duplicate customers remove karke clean independent DataFrame return karta hai.", "`subset`, `keep`, `ignore_index`, `inplace` pass kar sakte ho."),
      L(`def build_features(df: pd.DataFrame) -> pd.DataFrame:`, "Raw columns se model-like risk features banane ka function.", "`df` me validated columns expected hain."),
      L(`    out = df.copy()`, "Original DataFrame mutate hone se bachata hai.", "`deep=False` pass karke shallow copy possible hai, but default safer."),
      L(`    out["support_pressure"] = out["tickets_30d"] / np.maximum(out["monthly_spend"], 1)`, "Support tickets ko spend ke against normalize karta hai.", "`np.maximum` me scalar ya array pass kar sakte ho; yahan divide-by-zero avoid hota hai."),
      L(`    out["inactive_score"] = np.clip(out["days_since_login"] / 60, 0, 1)`, "Recent inactivity ko 0-1 score me cap karta hai.", "`np.clip(array, min, max)` me min/max business window ke hisab se change karo."),
      L(`    out["spend_rank"] = out["monthly_spend"].rank(pct=True)`, "Spend percentile nikalta hai taaki low spend ko extra risk signal mil sake.", "`method`, `ascending`, `na_option`, `pct` pass kar sakte ho."),
      L(`    out["risk_score"] = 0.50 * out["inactive_score"] + 0.35 * out["support_pressure"] + 0.15 * (1 - out["spend_rank"])`, "Weighted risk score combine karta hai.", "Weights business validation se tune karo; total usually 1 rakho."),
      L(`    out["risk_band"] = pd.cut(out["risk_score"], bins=[-np.inf, 0.35, 0.65, np.inf], labels=["low", "medium", "high"])`, "Numeric score ko business-friendly low/medium/high band me convert karta hai.", "`bins`, `labels`, `right`, `include_lowest`, `duplicates` pass kar sakte ho."),
      L(`    return out`, "Feature-added DataFrame caller ko return karta hai.", "Return se pipeline functions chainable rehte hain."),
      L(`def summarize(df: pd.DataFrame) -> pd.DataFrame:`, "Plan aur risk band level summary report banane ka function.", "`df` me `risk_band` aur churn columns expected hain."),
      L(`    summary = df.groupby(["plan", "risk_band"], observed=True).agg(customers=("customer_id", "count"), churn_rate=("is_churned", "mean"), avg_spend=("monthly_spend", "mean")).reset_index()`, "Grouped business metrics calculate karta hai.", "`groupby` me columns list; `agg` me count, mean, sum, median, custom lambda pass kar sakte ho."),
      L(`    return summary.sort_values(["plan", "risk_band"])`, "Report ko stable readable order me sort karta hai.", "`ascending`, `na_position`, `key` pass kar sakte ho."),
      L(`def plot_report(summary: pd.DataFrame, output: Path) -> None:`, "Summary DataFrame se chart image save karne ka function.", "`output` existing ya creatable folder hona chahiye."),
      L(`    pivot = summary.pivot(index="plan", columns="risk_band", values="churn_rate").fillna(0)`, "Long summary ko chart-friendly matrix me reshape karta hai.", "`pivot` me `index`, `columns`, `values`; duplicates ho to `pivot_table` use karo."),
      L(`    fig, ax = plt.subplots(figsize=(9, 5))`, "Figure aur axes object create karta hai using production-preferred OO API.", "`figsize`, `dpi`, `nrows`, `ncols`, `sharex`, `sharey` pass kar sakte ho."),
      L(`    pivot.plot(kind="bar", ax=ax, color=["#22c55e", "#f59e0b", "#ef4444"])`, "Plan-wise risk bands ka bar chart banata hai.", "`kind` me bar, line, area; `ax`, `color`, `stacked`, `rot` pass kar sakte ho."),
      L(`    ax.set_title("Churn rate by plan and risk band")`, "Chart ka title set karta hai.", "`loc`, `fontsize`, `fontweight`, `pad` pass kar sakte ho."),
      L(`    ax.set_ylabel("Churn rate")`, "Y-axis label set karta hai.", "`fontsize`, `labelpad`, `color` pass kar sakte ho."),
      L(`    ax.set_xlabel("Plan")`, "X-axis label set karta hai.", "`fontsize`, `labelpad`, `color` pass kar sakte ho."),
      L(`    ax.legend(title="Risk band")`, "Risk band legend add karta hai.", "`loc`, `title`, `frameon`, `ncol` pass kar sakte ho."),
      L(`    ax.grid(axis="y", alpha=0.25)`, "Y-axis grid add karke chart readable banata hai.", "`axis` x/y/both; `alpha`, `linestyle`, `linewidth` pass kar sakte ho."),
      L(`    fig.tight_layout()`, "Labels/title clipping avoid karta hai.", "`pad`, `w_pad`, `h_pad`, `rect` pass kar sakte ho."),
      L(`    fig.savefig(output / "churn_rate_by_plan.png", dpi=160, bbox_inches="tight")`, "Chart ko PNG file me save karta hai.", "`dpi`, `bbox_inches`, `transparent`, `facecolor`, `format` pass kar sakte ho."),
      L(`def main() -> None:`, "Script ka orchestration entrypoint.", "CLI args later add karne ho to `main(input_path, output_dir)` bana sakte ho."),
      L(`    REPORT_DIR.mkdir(parents=True, exist_ok=True)`, "Output folder create karta hai without failing if already exists.", "`parents`, `exist_ok`, `mode` pass kar sakte ho."),
      L(`    customers = load_customers(INPUT_FILE)`, "Raw input read and validate karta hai.", "`INPUT_FILE` ko config/env/CLI se replace kar sakte ho."),
      L(`    scored = build_features(customers)`, "Customer-level risk score and band generate karta hai.", "Feature weights build_features me tune hote hain."),
      L(`    summary = summarize(scored)`, "Aggregated business summary banata hai.", "Different group dimensions add kar sakte ho, jaise region/channel."),
      L(`    scored.to_csv(REPORT_DIR / "scored_customers.csv", index=False)`, "Customer-level scored output CSV me save karta hai.", "`index`, `columns`, `encoding`, `compression`, `date_format` pass kar sakte ho."),
      L(`    summary.to_csv(REPORT_DIR / "churn_summary.csv", index=False)`, "Aggregated summary CSV me save karta hai.", "`float_format` add karke decimal formatting control kar sakte ho."),
      L(`    plot_report(summary, REPORT_DIR)`, "Chart generation function call karta hai.", "Function me PNG ke saath PDF/SVG export bhi add kar sakte ho."),
      L(`    high_risk = scored[scored["risk_score"] >= CHURN_THRESHOLD]`, "Threshold ke basis pe high-risk customers filter karta hai.", "`>=` ko `>` ya band filter se replace kar sakte ho."),
      L(`    logging.info("High risk customers: %s", len(high_risk))`, "Run complete hone par actionable count log karta hai.", "Format string me multiple `%s` placeholders pass kar sakte ho."),
      L(`if __name__ == "__main__":`, "File directly run ho tabhi main execute karta hai.", "Import karne par side effects avoid hote hain."),
      L(`    main()`, "Script workflow start karta hai.", "Future me CLI parsed parameters yahan pass kar sakte ho."),
    ],
  },
  {
    slug: "sku-demand-forecast",
    title: "SKU Demand Forecast Baseline",
    level: "Intermediate",
    summary:
      "Order history se daily SKU demand banata hai, rolling-average baseline forecast karta hai, MAPE calculate karta hai, aur top SKU chart save karta hai.",
    businessUse:
      "Inventory team stock planning aur re-order quantity ka first baseline nikal sakti hai before advanced forecasting models.",
    stack: ["Python", "NumPy", "pandas", "Matplotlib"],
    files: [
      "data/orders.csv",
      "reports/demand/daily_forecast_backtest.csv",
      "reports/demand/next_14_days_forecast.csv",
      "reports/demand/top_sku_backtest.png",
    ],
    runCommand: "python demand_forecast.py",
    lines: [
      L(`from pathlib import Path`, "Input/output path handling ke liye Path import.", "`Path` local, absolute, relative, network-mounted paths handle kar sakta hai."),
      L(`import logging`, "Backtest metric aur run status log karne ke liye.", "`logging.info`, `warning`, `error` common methods hain."),
      L(`import numpy as np`, "MAPE, ceiling, safe division ke numeric operations ke liye.", "`np` alias standard hai."),
      L(`import pandas as pd`, "Orders CSV, date grouping, rolling features, exports ke liye.", "`pd` alias standard hai."),
      L(`import matplotlib.pyplot as plt`, "Forecast vs actual chart save karne ke liye.", "`plt` alias standard hai."),
      L(`INPUT_FILE = Path("data/orders.csv")`, "Raw orders data file configure karta hai.", "Yahan daily export CSV ya warehouse dump path de sakte ho."),
      L(`OUTPUT_DIR = Path("reports/demand")`, "Forecast reports ka output folder.", "Date or environment based output dir pass kar sakte ho."),
      L(`FORECAST_DAYS = 14`, "Future forecast horizon days me define karta hai.", "7, 14, 30, 90 jaise horizons business use case pe depend karte hain."),
      L(`WINDOW = 7`, "Rolling average ke liye lookback window.", "7 weekly pattern, 14 smoother, 28 monthly-ish trend ke liye."),
      L(`logging.basicConfig(level=logging.INFO, format="%(levelname)s:%(message)s")`, "Simple logger setup karta hai.", "`filename` pass karke logs file me bhi bhej sakte ho."),
      L(`def load_orders(path: Path) -> pd.DataFrame:`, "Order data load aur validation function.", "`path` ko CLI se inject karna easy hota hai."),
      L(`    df = pd.read_csv(path, parse_dates=["order_date"])`, "Orders CSV read karta hai aur order_date ko datetime banata hai.", "`parse_dates`, `usecols`, `dtype`, `chunksize` pass kar sakte ho."),
      L(`    required = {"order_date", "sku", "quantity"}`, "Forecast ke minimum columns define karta hai.", "Price, warehouse, channel jaise columns later add kar sakte ho."),
      L(`    missing = required - set(df.columns)`, "Schema mismatch detect karta hai.", "Set difference validation ka concise pattern hai."),
      L(`    if missing:`, "Missing columns ho to fail-fast guard.", "Bad data ko report generate karne se pehle stop karta hai."),
      L(`        raise ValueError(f"Missing columns: {sorted(missing)}")`, "Useful error message ke saath exception raise.", "Custom exception bhi use kar sakte ho."),
      L(`    df = df[df["quantity"] > 0].copy()`, "Returns/cancelled/zero rows ko baseline demand se remove karta hai.", "Condition business logic se tune ho sakti hai, jaise returns alag track karna."),
      L(`    return df`, "Clean orders DataFrame return karta hai.", "Return type `pd.DataFrame` function signature se clear hai."),
      L(`def daily_demand(df: pd.DataFrame) -> pd.DataFrame:`, "Raw orders ko daily SKU demand table me aggregate karta hai.", "`df` me `order_date`, `sku`, `quantity` columns expected."),
      L(`    daily = df.groupby(["sku", pd.Grouper(key="order_date", freq="D")])["quantity"].sum().reset_index()`, "SKU aur day level demand sum karta hai.", "`pd.Grouper` me `key`, `freq`, `closed`, `label`, `origin` pass kar sakte ho."),
      L(`    return daily.sort_values(["sku", "order_date"])`, "Forecasting ke liye chronological sorted output return.", "`ascending` list pass karke mixed sorting possible hai."),
      L(`def add_baseline_forecast(daily: pd.DataFrame) -> pd.DataFrame:`, "Rolling-average forecast aur errors add karta hai.", "`daily` one row per sku per day hona chahiye."),
      L(`    out = daily.copy()`, "Caller data mutate na ho isliye copy.", "`deep=False` shallow copy, default deep safer."),
      L(`    out["rolling_mean"] = out.groupby("sku")["quantity"].transform(lambda s: s.rolling(WINDOW, min_periods=1).mean())`, "Har SKU ke liye previous demand ka rolling mean signal banata hai.", "`rolling` me `window`, `min_periods`, `center`, `closed`; `transform` original row count preserve karta hai."),
      L(`    out["forecast"] = out.groupby("sku")["rolling_mean"].shift(1)`, "Aaj ka forecast kal tak ke data se banata hai, leakage avoid.", "`shift(periods=1)` default; negative shift future values la sakta hai, avoid for backtest."),
      L(`    out["forecast"] = out["forecast"].fillna(out["quantity"].median())`, "First row forecasts ko global median se fill karta hai.", "`fillna` me scalar, dict, method ffill/bfill pass kar sakte ho."),
      L(`    out["error"] = out["quantity"] - out["forecast"]`, "Actual minus forecast error calculate karta hai.", "Positive error means under-forecast; negative means over-forecast."),
      L(`    out["ape"] = np.abs(out["error"]) / np.maximum(out["quantity"], 1)`, "Absolute percentage error safe denominator ke saath.", "`np.maximum` zero demand division avoid karta hai."),
      L(`    return out`, "Backtest metrics attached DataFrame return karta hai.", "Later columns: bias, squared_error, stockout_flag add kar sakte ho."),
      L(`def next_period_forecast(scored: pd.DataFrame) -> pd.DataFrame:`, "Latest SKU forecast ko next N days ke grid me convert karta hai.", "`scored` me `forecast` and `order_date` columns expected."),
      L(`    latest = scored.groupby("sku").tail(1)[["sku", "forecast"]].copy()`, "Har SKU ka latest forecast pick karta hai.", "`tail(1)` last row; `nth(-1)` alternative hai."),
      L(`    future_dates = pd.date_range(scored["order_date"].max() + pd.Timedelta(days=1), periods=FORECAST_DAYS, freq="D")`, "Forecast horizon ke future dates generate karta hai.", "`date_range` me `start`, `end`, `periods`, `freq`, `tz` pass kar sakte ho."),
      L(`    forecast_grid = latest.merge(pd.DataFrame({"order_date": future_dates}), how="cross")`, "Har SKU ko har future date ke saath combine karta hai.", "`how='cross'` cartesian product; normal joins me `on`, `left_on`, `right_on`."),
      L(`    forecast_grid["forecast_qty"] = np.ceil(forecast_grid["forecast"]).astype(int)`, "Forecast quantity ko sellable integer units me round up karta hai.", "`np.ceil`, `np.floor`, `np.round` alternatives business rule pe depend karte hain."),
      L(`    return forecast_grid[["order_date", "sku", "forecast_qty"]]`, "Final forecast columns select karke return.", "Warehouse/channel columns add karne ho to selection me include karo."),
      L(`def plot_top_sku(scored: pd.DataFrame, output: Path) -> None:`, "Top SKU ke actual vs forecast chart banata hai.", "`output` folder pre-created hona chahiye."),
      L(`    top_sku = scored.groupby("sku")["quantity"].sum().idxmax()`, "Total quantity ke basis pe highest-volume SKU find karta hai.", "`idxmax` max label deta hai; min ke liye `idxmin`."),
      L(`    view = scored[scored["sku"] == top_sku].tail(60)`, "Last 60 days ka focused view chart ke liye.", "`tail(30)` ya date filter use kar sakte ho."),
      L(`    fig, ax = plt.subplots(figsize=(10, 5))`, "Chart canvas create karta hai.", "`figsize`, `dpi`, `nrows`, `ncols` options available."),
      L(`    ax.plot(view["order_date"], view["quantity"], label="Actual", linewidth=2)`, "Actual demand line plot karta hai.", "`label`, `linewidth`, `marker`, `color`, `linestyle` pass kar sakte ho."),
      L(`    ax.plot(view["order_date"], view["forecast"], label="Forecast", linewidth=2, linestyle="--")`, "Forecast line dashed style me plot karta hai.", "`linestyle` values: '-', '--', ':', '-.'."),
      L(`    ax.set_title(f"Demand forecast backtest: {top_sku}")`, "Dynamic SKU title set karta hai.", "`set_title` me `fontsize`, `fontweight`, `pad` pass kar sakte ho."),
      L(`    ax.set_ylabel("Units sold")`, "Y-axis business metric label.", "`labelpad` and `color` pass kar sakte ho."),
      L(`    ax.legend()`, "Actual and forecast labels show karta hai.", "`loc`, `ncol`, `frameon` pass kar sakte ho."),
      L(`    ax.grid(alpha=0.25)`, "Grid add karta hai for readable trend comparison.", "`axis`, `alpha`, `linestyle` pass kar sakte ho."),
      L(`    fig.autofmt_xdate()`, "Date labels rotate/align karta hai.", "`rotation`, `ha` pass kar sakte ho."),
      L(`    fig.tight_layout()`, "Chart spacing clean karta hai.", "`pad`, `rect` pass kar sakte ho."),
      L(`    fig.savefig(output / "top_sku_backtest.png", dpi=160, bbox_inches="tight")`, "Chart image save karta hai.", "`dpi`, `bbox_inches`, `transparent`, `format` pass kar sakte ho."),
      L(`def main() -> None:`, "End-to-end script runner define karta hai.", "CLI parameters later add kar sakte ho."),
      L(`    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)`, "Output folder recursively create karta hai.", "`parents=True` nested folders ke liye required hai."),
      L(`    orders = load_orders(INPUT_FILE)`, "Validated raw orders load karta hai.", "File path config se replace ho sakta hai."),
      L(`    daily = daily_demand(orders)`, "Raw orders ko daily SKU demand table me convert.", "Granularity weekly/monthly karne ke liye Grouper freq change karo."),
      L(`    scored = add_baseline_forecast(daily)`, "Backtest forecast and errors calculate.", "Advanced model later yahan replace kar sakte ho."),
      L(`    future = next_period_forecast(scored)`, "Next 14 days forecast table generate.", "`FORECAST_DAYS` config se horizon change hota hai."),
      L(`    scored.to_csv(OUTPUT_DIR / "daily_forecast_backtest.csv", index=False)`, "Backtest detail CSV save.", "`index=False` reporting files clean rakhta hai."),
      L(`    future.to_csv(OUTPUT_DIR / "next_14_days_forecast.csv", index=False)`, "Forward-looking demand forecast CSV save.", "`date_format` pass karke dates format kar sakte ho."),
      L(`    plot_top_sku(scored, OUTPUT_DIR)`, "Visual QA/report chart generate.", "Multiple SKU loop add kar sakte ho."),
      L(`    logging.info("Backtest MAPE: %.2f%%", scored["ape"].mean() * 100)`, "Average MAPE percent log karta hai.", "`%.2f` decimal formatting; more metrics log kar sakte ho."),
      L(`if __name__ == "__main__":`, "Direct execution guard.", "Module import karne par script auto-run nahi hogi."),
      L(`    main()`, "Forecast workflow execute karta hai.", "Later `main(input_file, output_dir)` bana kar args pass kar sakte ho."),
    ],
  },
  {
    slug: "lead-score-threshold-report",
    title: "Lead Score Threshold Report",
    level: "Industry",
    summary:
      "Prediction scores ka threshold sweep karta hai, precision/recall/F1 nikalta hai, best threshold choose karta hai, aur segment-level report export karta hai.",
    businessUse:
      "Sales team decide kar sakti hai ki kaunse score ke upar leads ko call queue me bhejna hai so revenue aur team capacity balance rahe.",
    stack: ["Python", "NumPy", "pandas", "Matplotlib"],
    files: [
      "data/lead_scores.csv",
      "reports/lead_scoring/threshold_metrics.csv",
      "reports/lead_scoring/segment_report.csv",
      "reports/lead_scoring/threshold_curve.png",
    ],
    runCommand: "python lead_score_threshold_report.py",
    lines: [
      L(`from pathlib import Path`, "Report paths ko robustly handle karne ke liye.", "`Path` slash operator se paths join karta hai."),
      L(`import numpy as np`, "Threshold grid aur vectorized metric calculations ke liye.", "`np.arange`, `np.sum`, boolean arrays yahan use honge."),
      L(`import pandas as pd`, "Prediction CSV read, report tables, groupby exports ke liye.", "`pd` alias standard hai."),
      L(`import matplotlib.pyplot as plt`, "Threshold performance curve plot karne ke liye.", "`plt` alias common hai."),
      L(`PREDICTIONS_FILE = Path("data/lead_scores.csv")`, "Input file jisme lead_id, segment, converted, score columns honge.", "Absolute path, S3-downloaded local path, ya dated batch path use kar sakte ho."),
      L(`REPORT_DIR = Path("reports/lead_scoring")`, "All generated threshold reports ka folder.", "Campaign/model version ke hisab se folder change kar sakte ho."),
      L(`THRESHOLDS = np.arange(0.10, 0.91, 0.05)`, "0.10 se 0.90 tak thresholds sweep karta hai.", "`start`, `stop`, `step`; `np.linspace(0.1, 0.9, 17)` alternative hai."),
      L(`def load_predictions(path: Path) -> pd.DataFrame:`, "Predictions CSV load and validate karta hai.", "`path` batch-specific file ho sakta hai."),
      L(`    df = pd.read_csv(path)`, "Prediction data read karta hai.", "`usecols`, `dtype`, `na_values`, `encoding` pass kar sakte ho."),
      L(`    required = {"lead_id", "segment", "converted", "score"}`, "Minimum expected schema define karta hai.", "Campaign, region, source columns extra allowed hain."),
      L(`    missing = required - set(df.columns)`, "Missing required columns calculate.", "Set operation simple schema validation hai."),
      L(`    if missing:`, "Bad input detect hone par branch.", "Non-empty missing set true hota hai."),
      L(`        raise ValueError(f"Missing columns: {sorted(missing)}")`, "Clear failure reason deta hai.", "Data pipeline me ye error upstream alert bana sakta hai."),
      L(`    if not df["score"].between(0, 1).all():`, "Scores 0-1 probability range me hain ya nahi check.", "`between(left, right, inclusive='both')` parameters support karta hai."),
      L(`        raise ValueError("score must be between 0 and 1")`, "Invalid probabilities pe fail-fast.", "Score scale 0-100 ho to pehle divide by 100 karo."),
      L(`    return df.dropna(subset=["converted", "score"]).copy()`, "Metric-critical null rows remove karke copy return.", "`subset`, `how`, `thresh` dropna options hain."),
      L(`def metrics_at_threshold(df: pd.DataFrame, threshold: float) -> dict[str, float]:`, "Single threshold ke metrics calculate karta hai.", "`threshold` 0-1 float; business capacity ke hisab se tune hota hai."),
      L(`    y_true = df["converted"].astype(bool).to_numpy()`, "Actual conversion labels boolean NumPy array me convert.", "`astype(int)` possible hai; boolean logical ops cleaner hain."),
      L(`    y_pred = (df["score"].to_numpy() >= threshold)`, "Threshold ke upar leads ko predicted positive mark.", "`>=` inclusive; `>` use karna bhi possible hai."),
      L(`    tp = np.sum(y_true & y_pred)`, "True positives: converted and selected.", "`&` element-wise AND; arrays same length honi chahiye."),
      L(`    fp = np.sum(~y_true & y_pred)`, "False positives: selected but convert nahi hue.", "`~` boolean NOT operator hai."),
      L(`    fn = np.sum(y_true & ~y_pred)`, "False negatives: convert hue but selected nahi hue.", "Recall calculate karne me use hota hai."),
      L(`    tn = np.sum(~y_true & ~y_pred)`, "True negatives: not converted and not selected.", "Accuracy/specificity ke liye useful."),
      L(`    precision = tp / max(tp + fp, 1)`, "Selected leads me se kitne actually converted.", "`max(..., 1)` divide-by-zero guard hai."),
      L(`    recall = tp / max(tp + fn, 1)`, "Actual converted leads me se kitne catch hue.", "High recall means fewer missed opportunities."),
      L(`    f1 = 2 * precision * recall / max(precision + recall, 1e-12)`, "Precision-recall balance score.", "`1e-12` zero denominator guard hai."),
      L(`    selection_rate = (tp + fp) / len(df)`, "Total leads me se kitne sales queue me jayenge.", "Capacity planning ke liye important metric."),
      L(`    return {"threshold": threshold, "precision": precision, "recall": recall, "f1": f1, "selection_rate": selection_rate, "tp": tp, "fp": fp, "fn": fn, "tn": tn}`, "Metrics dict return karta hai for DataFrame conversion.", "More metrics add kar sakte ho: accuracy, specificity, revenue, cost."),
      L(`def build_threshold_table(df: pd.DataFrame) -> pd.DataFrame:`, "Saare thresholds ke metrics table banata hai.", "`df` predictions DataFrame hai."),
      L(`    rows = [metrics_at_threshold(df, t) for t in THRESHOLDS]`, "List comprehension se each threshold evaluate.", "`THRESHOLDS` ko custom array/list se replace kar sakte ho."),
      L(`    return pd.DataFrame(rows)`, "Rows list ko tabular report me convert.", "`columns` parameter se order force kar sakte ho."),
      L(`def segment_report(df: pd.DataFrame, threshold: float) -> pd.DataFrame:`, "Best threshold pe segment-wise impact report banata hai.", "`threshold` chosen operating point hota hai."),
      L(`    tagged = df.assign(predicted_conversion=df["score"] >= threshold)`, "Boolean selected flag add karta hai without mutating original.", "`assign` me multiple new columns and lambdas pass kar sakte ho."),
      L(`    return tagged.groupby("segment").agg(leads=("lead_id", "count"), avg_score=("score", "mean"), selected=("predicted_conversion", "sum"), actual_conversion_rate=("converted", "mean")).reset_index()`, "Segment level count, average score, selected leads, conversion rate aggregate.", "`agg` me sum, mean, median, nunique, lambda pass kar sakte ho."),
      L(`def plot_thresholds(table: pd.DataFrame, output: Path) -> None:`, "Threshold metrics curve plot and save karta hai.", "`table` build_threshold_table output hai."),
      L(`    fig, ax = plt.subplots(figsize=(9, 5))`, "Figure and axes create.", "`figsize`, `dpi`, `layout` pass kar sakte ho."),
      L(`    ax.plot(table["threshold"], table["precision"], marker="o", label="Precision")`, "Precision trend draw karta hai.", "`marker`, `color`, `linewidth`, `label` pass kar sakte ho."),
      L(`    ax.plot(table["threshold"], table["recall"], marker="o", label="Recall")`, "Recall trend draw karta hai.", "Same axes pe compare karne ke liye label important hai."),
      L(`    ax.plot(table["threshold"], table["f1"], marker="o", label="F1")`, "F1 trend draw karta hai.", "Best threshold often F1 peak se choose hota hai."),
      L(`    ax.set_xlabel("Threshold")`, "X-axis label.", "`fontsize`, `labelpad` pass kar sakte ho."),
      L(`    ax.set_ylabel("Metric value")`, "Y-axis label.", "`set_ylim(0, 1)` add kar sakte ho."),
      L(`    ax.set_title("Lead score threshold sweep")`, "Chart title.", "`loc`, `fontweight`, `pad` options available."),
      L(`    ax.legend()`, "Precision/Recall/F1 legend show karta hai.", "`loc`, `frameon`, `ncol` pass kar sakte ho."),
      L(`    ax.grid(alpha=0.25)`, "Grid se metric comparison easy hota hai.", "`axis`, `linestyle`, `linewidth` pass kar sakte ho."),
      L(`    fig.tight_layout()`, "Spacing clean karta hai.", "`pad`, `rect` pass kar sakte ho."),
      L(`    fig.savefig(output / "threshold_curve.png", dpi=160, bbox_inches="tight")`, "Curve PNG report folder me save.", "`dpi`, `bbox_inches`, `transparent`, `format` pass kar sakte ho."),
      L(`def main() -> None:`, "Script ke full report workflow ka entrypoint.", "Input/output parameters later inject kar sakte ho."),
      L(`    REPORT_DIR.mkdir(parents=True, exist_ok=True)`, "Report directory create karta hai.", "`parents=True` nested folders banata hai; `exist_ok=True` existing folder pe error nahi."),
      L(`    predictions = load_predictions(PREDICTIONS_FILE)`, "Validated predictions load karta hai.", "Batch file path config se aata hai."),
      L(`    threshold_table = build_threshold_table(predictions)`, "All threshold metrics calculate karta hai.", "Threshold grid global constant se driven hai."),
      L(`    best = threshold_table.iloc[threshold_table["f1"].idxmax()]`, "Best F1 row select karta hai.", "`idxmax` ke badle custom business utility score use kar sakte ho."),
      L(`    segments = segment_report(predictions, float(best["threshold"]))`, "Chosen threshold par segment report banata hai.", "`float` NumPy scalar ko Python float me convert karta hai."),
      L(`    threshold_table.to_csv(REPORT_DIR / "threshold_metrics.csv", index=False)`, "Threshold sweep results CSV save.", "`index`, `float_format`, `columns` pass kar sakte ho."),
      L(`    segments.to_csv(REPORT_DIR / "segment_report.csv", index=False)`, "Segment-level business report save.", "`encoding` and `float_format` reporting polish ke liye useful."),
      L(`    plot_thresholds(threshold_table, REPORT_DIR)`, "Metric curve image save karta hai.", "Plot me vertical best-threshold line add kar sakte ho."),
      L(`    print(f"Best threshold: {best['threshold']:.2f}, F1: {best['f1']:.3f}")`, "Terminal pe final operating point print karta hai.", "Logging ya JSON output use kar sakte ho automation ke liye."),
      L(`if __name__ == "__main__":`, "Direct run guard.", "Import karne par main auto-run nahi hoga."),
      L(`    main()`, "End-to-end threshold report execute karta hai.", "Future me argparse values yahan pass ho sakti hain."),
    ],
  },
];

export function projectCode(project: IndustryProject): string {
  return project.lines.map((line) => line.code).join("\n");
}
